workspace_dir: ./ml_dev_bench/cases/dataset/dataset_not_available_download/workspace
output_dir: ./ml_dev_bench/cases/dataset/dataset_not_available_download/results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-dataset-not-available-download"

task_packages:
  - "ml_dev_bench.cases.dataset.dataset_not_available_download"

agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "anthropic/claude-3-5-haiku-20241022"

tasks:
  - id: "dataset_not_available_download"
