workspace_dir: ./ml_dev_bench/cases/dataset/dataset_not_available_download/workspace
output_dir: ./ml_dev_bench/cases/dataset/dataset_not_available_download/results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-dataset-not-available-download"

task_packages:
  - "ml_dev_bench.cases.dataset.dataset_not_available_download"

agent_packages:
  - "agents.aide_ml_agent"

# Agent configuration

agent:
  id: "aide_ml_agent"
  model_name: "gpt-4o"


tasks:
  - id: "dataset_not_available_download"
