workspace_dir: ./workspace
output_dir: ./results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-training-logs"
clone_workspace: true  # clones workspace to a temporary directory
clone_workspace_to: "/workspace"
clear_workspace: true

task_packages:
  - "ml_dev_bench.cases.training.parse_logs"

# Agent configuration
agent_packages:
  - "agents.openhands_agent"

# Agent configuration
agent:
  id: "openhands_agent"
  model_name: "anthropic/claude-3-5-sonnet-20241022"


tasks:
  - id: parse_logs
