workspace_dir: ./workspace
output_dir: ./results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-training-logs"

task_packages:
  - "ml_dev_bench.cases.training.parse_logs"

agent_packages:
  - "agents.aide_ml_agent"

agent:
  id: "aide_ml_agent"
  model_name: "gpt-4o"

tasks:
  - id: parse_logs
