# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./workspace"
langchain_project: "pascalvoc-segmentation"

# Task package imports
task_packages:
  - "ml_dev_bench.cases.improve_baseline.segmentation"

clone_workspace: true  # clones workspace to a temporary directory
clone_workspace_to: "/workspace"
clear_workspace: true

# Agent configuration
agent_packages:
  - "agents.openhands_agent"

# Agent configuration
agent:
  id: "openhands_agent"
  model_name: "anthropic/claude-3-5-sonnet-20241022"


# Task configurations
tasks:
  - id: "improve_segmentation_baseline"
