# Core evaluation settings
num_runs: 1
fail_fast: true
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./ml_dev_bench/cases/modify_existing_model/channel_vit/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-channel-vit"
clone_workspace: true

# Task package imports
task_packages:
  - "ml_dev_bench.cases.modify_existing_model.channel_vit_easy"

clone_workspace_to: "/workspace"
clear_workspace: true

# Agent configuration
agent_packages:
  - "agents.openhands_agent"

# Agent configuration
agent:
  id: "openhands_agent"
  model_name: "anthropic/claude-3-5-sonnet-20241022"

# Task configurations
tasks:
  - id: "channel_vit_implementation_easy"
