workspace_dir: ./test_workspace
output_dir: ./ml_dev_bench/cases/training/small_dataset_overfit/results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-small-dataset-overfit"

task_packages:
  - "ml_dev_bench.cases.training.small_dataset_overfit"

agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "anthropic/claude-3-5-sonnet-20241022"
  recursion_limit: 30

tasks:
  - id: small_dataset_overfit
