# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./workspace"
langchain_project: "ml-dev-bench-evaluation-small-dataset-overfit"

clone_workspace: true  # clones workspace to a temporary directory
clone_workspace_to: "/workspace"
clear_workspace: true

# Task package imports
task_packages:
  - "ml_dev_bench.cases.training.small_dataset_overfit"

# Agent configuration
agent_packages:
  - "agents.openhands_agent"

agent:
  id: "openhands_agent"
  model_name: "anthropic/claude-3-5-sonnet-20241022"

# Task configurations
tasks:
  - id: small_dataset_overfit 