# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./test_workspace"
langchain_project: "ml-dev-bench-evaluation-pretrained-bert-base-uncased-load"

# Task package imports
task_packages:
  - "ml_workflow_bench.cases.training.pretrained_bert_base_uncased_load"

# Agent configuration
agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "gpt-4o-mini"
  executor_recursion_limit: 25
  workflow_recursion_limit: 60

# Task configurations
tasks:
  - id: pretrained_bert_base_uncased_load
