# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./workspace"
langchain_project: "ml-dev-bench-evaluation-basic-vision-finetuning"

# Task package imports
task_packages:
  - "ml_dev_bench.cases.training.basic_vision_finetuning"

# Agent configuration
agent_packages:
  - "agents.aide_ml_agent"

agent:
  id: "aide_ml_agent"
  model_name: "gpt-4o"

# Task configurations
tasks:
  - id: basic_vision_finetuning
