# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./test_workspace"
langchain_project: "ml-dev-bench-evaluation-basic-vision-finetuning"

# Task package imports
task_packages:
  - "ml_workflow_bench.cases.training.basic_vision_finetuning"

# Agent configuration
agent:
  id: "oh_agent"
  agent_type: "plan_and_execute"
  planner_model: "anthropic/claude-3-5-haiku-20241022"
  executor_model: "anthropic/claude-3-5-haiku-20241022"
  replanner_model: "anthropic/claude-3-5-haiku-20241022"
  executor_recursion_limit: 60
  workflow_recursion_limit: 60

# Task configurations
tasks:
  - id: basic_vision_finetuning
