workspace_dir: ./workspace
output_dir: ./results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-dataset-preprocess"
clone_workspace: true  # clones workspace to a temporary directory
clone_workspace_to: "/workspace"
task_packages:
  - "ml_dev_bench.cases.dataset.dataset_preprocess"
clear_workspace: true

# Agent configuration
agent_packages:
  - "agents.openhands_agent"

# Agent configuration
agent:
  id: "openhands_agent"
  model_name: "anthropic/claude-3-5-sonnet-20241022"


tasks:
  - id: dataset_preprocess
    config:
      preprocessing:
        expected_shape: [3, 32, 32]
        value_range: [-1, 1]
        normalization:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
      augmentation:
        num_samples: 5  # Number of augmented versions to check
        variance_threshold: 0.1  # Minimum variance threshold
        success_threshold: 0.9  # Required success rate for augmentations
        transforms:
          rotation_degrees: 15
          color_jitter:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
