# Core evaluation settings
num_runs: 1
fail_fast: true
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./ml_dev_bench/cases/modify_existing_model/channel_vit/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-channel-vit"
clone_workspace: true

# Task package imports
task_packages:
  - "ml_workflow_bench.cases.modify_existing_model.channel_vit"

# Agent configuration
agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "gpt-4o-mini"
  executor_recursion_limit: 25
  workflow_recursion_limit: 30

# Task configurations
tasks:
  - id: "channel_vit_implementation"
