workspace_dir: ./ml_dev_bench/cases/training/multi_gpu_training/setup_workspace
output_dir: ./ml_dev_bench/cases/training/multi_gpu_training/results
fail_fast: false
log_level: "INFO"
num_runs: 1
langchain_project: "ml-dev-bench-evaluation-multi-gpu-training"

task_packages:
  - "ml_dev_bench.cases.training.multi_gpu_training"

agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "gpt-4o-mini"


tasks:
  - id: multi_gpu_training
