_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_loss_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_acc_step
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 106
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.6
            "5": 0.18.5
            "6": 4.47.1
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-x86_64
learning_rate:
    value: 0.001
num_classes:
    value: 10
