# Core evaluation settings
num_runs: 1
fail_fast: true
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./ml_dev_bench/cases/modify_existing_model/var/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-var"
clone_workspace: true

# Task package imports
task_packages:
  - "ml_dev_bench.cases.modify_existing_model.var"

# Agent configuration
agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "anthropic/claude-3-5-sonnet-20241022"
  recursion_limit: 50

# Task configurations
tasks:
  - id: "var_implementation"
