# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./evaluation/ml_debugging/nan_losses/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-nan-losses"
clone_workspace: true  # clones workspace to a temporary directory

# Task package imports
task_packages:
  - "ml_debugging.nan_losses"

# Agent configuration
agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "gpt-4o-mini"
  executor_recursion_limit: 25
  workflow_recursion_limit: 30

# Task configurations
tasks:
  - id: "nan_loss_debug"
