# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./evaluation/ml_debugging/shape_mismatch/cases/train_shape_error/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-shape-debug-train"
clone_workspace: true  # clones workspace to a temporary directory

# Task package imports
task_packages:
  - "ml_debugging.shape_mismatch.cases.train_shape_error"

# Agent configuration
agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "gpt-4o-mini"
  executor_recursion_limit: 25
  workflow_recursion_limit: 30

# Task configurations
tasks:
  - id: "shape_mismatch_train"
