# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./ml_dev_bench/cases/debugging/shape_mismatch/cases/train_shape_error/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-shape-debug-train"

clone_workspace: true  # clones workspace to a temporary directory
clone_workspace_to: "/workspace"
clear_workspace: true

# Task package imports
task_packages:
  - "ml_dev_bench.cases.debugging.shape_mismatch.cases.train_shape_error"

# Agent configuration
agent_packages:
  - "agents.openhands_agent"

agent:
  id: "openhands_agent"
  model_name: "anthropic/claude-3-5-sonnet-20241022"

# Task configurations
tasks:
  - id: "shape_mismatch_train" 