# Core evaluation settings
num_runs: 1
fail_fast: false
log_level: "INFO"
output_dir: "./results"
workspace_dir: "./ml_dev_bench/cases/debugging/bert_eval_debug/setup_workspace"
langchain_project: "ml-dev-bench-evaluation-bert-eval-debug"
clone_workspace: true  # clones workspace to a temporary directory

# Task package imports
task_packages:
  - "ml_dev_bench.cases.debugging.bert_eval_debug"

# Agent configuration
agent_packages:
  - "agents.react_agent"

# Agent configuration
agent:
  id: "simple_react"
  model_name: "anthropic/claude-3-5-sonnet-20241022"
  recursion_limit: 50

# Task configurations
tasks:
  - id: "bert_eval_debug"
